name: "ejsokms action"
description: "Execute encryption and decryption of ejsonkms file"

branding:
  icon: database
  color: blue

inputs:
  action:
    description: "Possible values should be encrypt or decrypt"
    required: true
  file-path:
    description: "Path to the source ejsonkms file"
    required: true
  aws-region:
    description: "AWS region. Only required if `action` is `decrypt`"
    required: false
  out-file:
    description: "File path to an out json file that should be use to place the decrypted content of the ejson"
    required: false
  populate-env-vars:
    description: "Populate the environment variables with the decrypted key-pairs content"
    required: false
  prefix-env-vars:
    description: "Add a prefix to the environment variables"
    required: false

outputs:
  decrypted:
    description: "Decrypted JSON content"
    value: "decrypt"

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v5
      with:
        node-version: 22
    - name: Install npm dependencies
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: npm ci
    - name: Install ejsonkms
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: install-deps.sh
    - name: Decrypt secrets
      id: decrypt
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: node index.js
